step1 구구단
pih6585/tdd_test pull request #2
Opened 2021-08-28 04:22 UTC by kth4878

1. README TODO-LIST 추가
2. 구구단 TEST 코드 추가
3. Product 코드 추가

2021-08-28 04:49 UTC, pih6585 requested changes

2021-08-28 04:49 UTC, pih6585 commented on README.md
> +  * 컨트롤러(모델과 뷰 사이의 중재자(Controller))
### TODO LIST
- [x] 이름을 입력하면 이름이 생성된다.
- [x] 이름은 영어만 가능하다.
- [x] 이름은 3글자이다.
- [x] 플레이어를 입력받는다.
- [x] 플레이어는 이름으로 구성되어 있다. 
- [x] 프레임 투구를 입력 받는다.
- [x] 핀을 만들어서 핀을 관리한다.
- [x] 핀은 0~10개로 구성되있다.
- [x] 핀은 양수이다.
- [x] 프레임의 게임을 관리하고 한 프레임당 종료 및 시작을 알아야 한다.
- [x] 룰의 따라 프레임의 게임은 normal 은 최대 10, final 은 최대 20이다.  
- [x] 프레임의 핀의 결과를 담당하는 부분이 있어야한다.
- [x] 총 라운드는 10라운드 이다.
todoList 예시입니다.

2021-08-28 04:49 UTC, pih6585 commented on src/main/java/multiplication/Message/MultipleMessage.java
> +	}
enum을 사용한 이유가 무엇인가요? 
메세지를 객체화하면 불필요한 instance가 발생이 될텐데  자원낭비가 심하겠죠?
그리고 toString override는 왜 있는건가요? 원시값은 getter를 사용해야됩니다.
static final을 이용한 상수를 접근하면 됩니다.

2021-08-28 04:49 UTC, pih6585 commented on src/main/java/multiplication/MultiplyApplication.java
> +	}
main에 view만있네요
controller는 어디있나요?

2021-08-28 04:49 UTC, pih6585 commented on src/main/java/multiplication/service/MultipliceService.java
> +
서비스가 왜필요한거죠
제일 작은 엔티티 부터 생각하시면 될것 같아요
서비스에 대한정의도 공부해보세요~

2021-08-28 04:49 UTC, pih6585 commented on src/main/java/multiplication/service/MultipliceService.java
> +		return false;
throw by를 이용한 validation을 공부해보세요
그리고 if문안에 null equals, length는 3가지 일을 하고있습니다.
그리고 equals("")은 정말 좋지않죠 isEmpty등 stirng에서 사용할 수있는 함수를 사용하세요

2021-08-28 04:49 UTC, pih6585 commented on src/main/java/multiplication/view/MultipleInputView.java
> +		String player = scan.nextLine();
상수를 이용하여 지역변수의 변경요소를 제거해주세요

2021-08-28 04:49 UTC, pih6585 commented on src/main/java/multiplication/view/MultipleInputView.java
> +		mrv.printNumberResult(number);
scan에 int가 안들어오면 예외가 발생하겠군요

2021-08-28 04:49 UTC, pih6585 commented on src/main/java/multiplication/view/MultipleInputView.java
> +		MultipleResultView mrv = new MultipleResultView();
전체적으로 네이밍을 축약해서 쓰는데 축약을 하면 안됩니다.

2021-08-28 04:49 UTC, pih6585 commented on src/main/java/multiplication/view/MultipleInputView.java
> +		MultipleResultView mrv = new MultipleResultView();
상태값을 안하는 클래스를 궃이 인스턴스화 할 필요가 없습니다.

2021-08-28 04:49 UTC, pih6585 commented on src/main/java/multiplication/view/MultipleResultView.java
> +		}
exit가 왜 필요한지 모르겠군요 throw을 통한 에러없는 프로그램을 만들어야되지 않을까요?
그리고 controller에 view에 대한 행위가 있으면 안됩니다.
mvc에 대한 이해도도 필요합니다.

2021-08-28 04:52 UTC, pih6585 commented
* 모든 문자열의 원시값을 포장한다.
* 일급 콜렉션을 사용한다.
이런 제약조건이 있으면 위에 해당사항들을 다루는데 더익숙해 질것 같아요~ 이규칙도 적용해주세요

2021-08-28 05:05 UTC, pih6585 requested changes

2021-08-28 05:05 UTC, pih6585 commented on src/main/java/multiplication/Message/MultipleMessage.java
> +	}
상수에 대한 이해도도 필요할것 같습니다.

2021-08-28 05:05 UTC, pih6585 commented on src/main/java/multiplication/calculator/Calculation.java
> +                .orElseThrow(() -> new IllegalArgumentException("올바른 연산자가 아닙니다."));
이런 메세지 부분도 상수화 처리하면 되겠군요

2021-08-28 05:05 UTC, pih6585 commented on src/main/java/multiplication/service/MultipliceService.java
> +		return false;
만약 String,valueOf(args.split(",")) 은 몇개의 일일까요
그리고 만약 프로그램시 위의 규칙을 수정해야할 일이 생길경우 단일책임원칙에 위배 됩니다.

2021-08-28 05:05 UTC, pih6585 commented on src/main/java/multiplication/service/MultipliceService.java
> +		}
이부분도 예외가 발생되었을때 throw를 사용하면 되겠군요

2021-08-28 05:05 UTC, pih6585 commented on src/main/java/multiplication/service/MultipliceService.java
> +		List<String> list = new ArrayList<String>();
현재에는 new ArrayList<>(); 타입을 주지않습니다. 자바 7,8버전의 사용법도 익히는게 좋겠어요

2021-08-28 05:05 UTC, pih6585 commented on src/main/java/multiplication/service/MultipliceService.java
> +		List<String> list = new ArrayList<String>();
그리고 list라는 naming은 지향하는게 좋습니다. 코딩컨벤션을 확인해주세요.
결과값을 반환하니까 
resulst가 맞겠군요
그리고 해당 add에서는 view에서 해야될 작업 아닌가요? 왜 여기서 view에 대한 일을 하고 있나요?

2021-08-28 05:05 UTC, pih6585 commented on src/main/java/multiplication/view/MultipleInputView.java
> +		MultipleResultView mrv = new MultipleResultView();
view에서 scanner를 호출했을때 다른 method가 생성시 scanner를 또 호출해야되는 상황이 발생되네요
이런 재활용적인 측면도 다 수정 부탁드립니다.

2021-08-28 05:05 UTC, pih6585 commented on src/test/java/multiplication/MultipleTest.java
> +	}
assertThat을 통해서 사용해보세요
그리고 player에 대한 예외가 검증이 되어야 하는데 service를 호출하네요?

2021-08-28 05:05 UTC, pih6585 commented on src/test/java/multiplication/MultipleTest.java
> +	}
또한 player에 값이 hyun이라고 확신할수 있나요? 그런테스트는 없네요
number, range도 마찬가지입니다.

2021-08-28 06:41 UTC, pih6585 commented on src/main/java/multiplication/MultiplyApplication.java
> +	}
controller는 view에 데이터를 전달하고 model에서 데이터를 받아오죠~
웹에서 실행할떄 우리가 controller의 주소를 불러오지 jsp나 html의 view 주소를 불러오진않죠~

2021-08-30 07:31 UTC, kth4878 commented
2021-08-30 코드수정

2021-08-30 08:59 UTC, pih6585 requested changes

2021-08-30 08:59 UTC, pih6585 commented on README.md
> +* 구구단의 숫자 및 범위 를 입력받는다.
- [] 경기당 경기결과를 반환한다. 
- 이런식의 todo list로 했는지 안했는지 결과를 확인하는게 더좋아요

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/ExceptionMessage.java
> +	public static final String MAX_NUMBER_ERROR_MESSAGE = "최대입력 가능한 숫자보다 입력한 숫자가 큽니다.";
Exception Error Message는 해당 클래스에서 private로 사용하는게제일 좋아요

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/MultipliceValue.java
> +		this.multipliceResult = multipliceResult;
클래스 이름이 이상한거같아요....
그리고 해당 일급 클래스는 불변이 아니여서 언제든지 수정이 가능하네요
해당 아래의 numberRange가 더 어울리고 아래의 NumberRange가 Number라는 클래스가 되야되지않을까요?
그리고 List<Number>가 되야 할거같아요

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/Name.java
> +			checkNameNull(name);
try catch가 왜 필요한거죠?
그리고 ExceptionMessage는 public static인데 인스턴스를 왜 사용한거죠?

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/Name.java
> +		if(name.length() > 5){
여기도 상수로 표현해봐요

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/NumberRange.java
> +	private String number;
final이 빠져있네요

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/NumberRange.java
> +	private static ExceptionMessage message = new ExceptionMessage();
여기서 불필요한 인스턴스 생성이 있군요
위에 코멘트를 참고하시고 클래스 명이 이상해요

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/NumberRange.java
> +	public NumberRange(String number) {
여기도 try catch가 왜 필요한거죠?

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/NumberRange.java
> +		int isNumeric = Integer.parseInt(number);
여기서 왜 Integer.parse를 하는거죠?
parse에서 오류가 발생하면 어떻게 할가죠?

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/NumberRange.java
> +		int isNumeric = Integer.parseInt(number);
이건 2가지일을 하는거예요

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/NumberRange.java
> +		boolean isNumeric = number.matches("[+-]?\\d*(\\.\\d+)?");
정규표현식이 너무 목잡하네요.  
정규표현식을 알아보세요 그리고 pattern을 이용하세요

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/NumberRange.java
> +		int numberOne = Integer.parseInt(number);
이 메서드는 여기서 해야할 일이 아닌거같은데요??
원시값이에서 List를 만드는 행위는 원시값에서 하는 일이아니죠
parse를 계속하는데 이부분도 한곳에서 처리를 해보세요.

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/NumberRange.java
> +		int numberOne = Integer.parseInt(number);
원시값은 말그대로 원시값입니다. 이부분도 확인해보세요

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/domain/NumberRange.java
> +		return new MultipliceValue(result).getMultipliceValue();
이행위조차도 말이 안되는 행위에여

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/view/MultipliceInputView.java
> +
view에서 controller를 왜불러오져?

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/view/MultipliceInputView.java
> +
제가 저번에 써드린 mvc의 글을 읽어보세요.
view는 controller에서 model의 데이터를 전달해서 받은 데이터로 출력을 해야합니다.

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/view/MultipliceInputView.java
> +
더군다나 input에서는 controller가 더욱더 필요없죠

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/view/MultipliceResultView.java
> +	public void printUserNameResult(String name) {
여기도 위에와 마찬가지 입니다.

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/controller/MultipliceController.java
> +	private final MultipliceResultView multipliceResultView = new MultipliceResultView();
view를 인스턴스 생성을 할 필요가 있을까요?

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/controller/MultipliceController.java
> +	public void run() { multipliceInputView.printMultipleInputView(); }
run에서 input view만 실행하네요

2021-08-30 08:59 UTC, pih6585 commented on src/main/java/multiplication/controller/MultipliceController.java
> +		new Name(name);
checkName은 name에서 이루어지는 행위 아닌가요?

2021-08-30 08:59 UTC, pih6585 commented on src/test/java/multiplication/MultipleTest.java
> +	private String userName;
모든 테스트 규칙은 해당 클래스에서 해당 클래스만 테스트 해야됩니다.
전체적인 테스트하는 방법도 이해가 안되어 있는것 같아요

2021-08-30 08:59 UTC, pih6585 commented
name 생성하는부분도 없고 전체적으로 어떻게 접근하는지 이해가 안되는것 같아요...

2021-09-02 01:56 UTC, merged