Step2 - 주사위게임
pih6585/tdd_test pull request #5
Opened 2021-09-04 06:25 UTC by kth4878

주사위게임 입니다.

2021-09-15 12:21 UTC, pih6585 commented
전체적으로 구현은 정말 많이 바뀌고 노력한게 보여서 좋다
지금 보면 너무 좀 복잡하고 get이 많이 사용되는데
dice와 name을 하나로 묶어서 관리하면 더좋을거 같고 그러면 names나 scores 등의 컬렉션이
사라지게끔 설계가 될것 같음.

2021-09-15 12:26 UTC, pih6585 requested changes

2021-09-15 12:26 UTC, pih6585 commented on src/main/java/dice/domain/game/DiceRoll.java
> +	private final int diceValue;
이 class의 의미를 모르겠어요~

2021-09-15 12:26 UTC, pih6585 commented on src/main/java/dice/domain/game/DiceResult.java
> +	public DiceResult() {
이부분은 필요없을거 같아요

2021-09-15 12:26 UTC, pih6585 commented on src/main/java/dice/domain/game/DiceResult.java
> +		return diceResult;
이부분도요~

2021-09-15 12:26 UTC, pih6585 commented on src/main/java/dice/domain/game/Dices.java
> +
dice와 name을 합친 class가 있으면 dices나 names나 이런부분들이 점진적으로 해결될거 같음

2021-09-15 12:26 UTC, pih6585 commented on src/main/java/dice/domain/game/Score.java
> +
이 클래스도 필요할까? 고민해보면 좋을거같음

2021-09-15 12:26 UTC, pih6585 commented on src/main/java/dice/domain/winner/Winner.java
> +	private final String name;
이부분은 객체로 관리안하고 service로만 있어도 될거같음

2021-09-15 12:26 UTC, pih6585 commented on src/main/java/dice/domain/winner/Winners.java
> +	private final List<Winner> winners;
이부분도 마찬가지로 객체로 관리안하고 service로만 있어도 될거같음

2021-09-15 12:26 UTC, pih6585 commented on src/main/java/dice/service/DiceService.java
> +		}
getter 지옥임...

2021-09-15 12:26 UTC, pih6585 commented on src/main/java/dice/service/DiceService.java
> +			.collect(Collectors.toList());
getter가 너무 많아요~

2021-09-15 12:26 UTC, pih6585 commented on src/main/java/dice/service/DiceService.java
> +			.collect(Collectors.toList());
메세지를 하위에 보내서 처리하게끔 하면 깔끔해져요

2021-09-15 12:26 UTC, pih6585 commented on src/main/java/dice/view/ResultView.java
> +			dices.getDices().get(number).getFirstDice() + " - " +
여기도 getter가 너무많아요~

2021-09-17 09:22 UTC, pih6585 commented
내가 말한건 Dice와 Name 객체는 그대로 사용하고
그걸 합친 class를말한건데 이해를 잘못한것 같고
score라는 변수가 궃이 필요한가? 그 클래스가 궃이 필요한가 생각해보라고 한거예요

2021-09-23 05:36 UTC, pih6585 requested changes

2021-09-23 05:36 UTC, pih6585 commented on src/main/java/dice/domain/DiceResult.java
> +	private final int diceResult;
random 관련된 static 으로 메모리에 올려놔서 사용하면 좀 더 좋을것 같아요.
안에 불필요한 method도 많은것 같아요

2021-09-23 05:36 UTC, pih6585 commented on src/main/java/dice/domain/PlayerScore.java
> +	private final int score;
인스턴스 변수가 너무많아요 Dice라는 객체를 왜 삭제했은지 이해가 안가요

2021-09-23 05:36 UTC, pih6585 commented on src/main/java/dice/view/InputView.java
> +	private static String checkNameLength() {
name이란 객체를 없애서 불필요하게 view에서 비즈니스 로직이 들어감
이거는 해당 name이란 객체에서 해야될일로 보여집니다.

2021-09-23 05:36 UTC, pih6585 commented on src/main/java/dice/view/InputView.java
> +	private static String checkNameLength() {
밑에 있는 로직도 마찬가지구요

2021-09-23 05:50 UTC, pih6585 requested changes

2021-09-23 05:50 UTC, pih6585 commented on src/main/java/dice/domain/DiceResult.java
> +	private final int diceResult;
이부분은 수정이 안되어있네요. 지금 구조에선 new DiceResult를 계속해서 인스턴스 생성이 되는 구조로
저번에 설명드린 부분이 전혀 반영이 안되어있는데 왜 고치지 않은지 코멘트를 남겨주세요

2021-09-23 05:50 UTC, pih6585 commented on src/main/java/dice/service/DiceService.java
> +	public static List<PlayerScore> diceGamePlay(List<String> names){
코드 컨벤션이 지켜지지않았아요. IDE의 툴을 이용하여 코딩컨벤션을 지켜주세요.

2021-09-23 05:50 UTC, pih6585 commented on src/main/java/dice/service/DiceService.java
> +	public static List<PlayerScore> diceGamePlay(List<String> names){
전체적으로 띄어쓰기가 안되어있네요

2021-09-23 05:50 UTC, pih6585 commented on src/main/java/dice/service/DiceService.java
> +			.mapToObj(i -> scoreByPlayer.get(i).getName())
불필요한 getter가 보이네요.
객체지향 생활 체조 원칙 9 :getter/setter/property를 쓰지 않는다. 
를 지켜보시는게 좋을것 같아요

2021-09-23 05:50 UTC, pih6585 commented on src/main/java/dice/view/InputView.java
> +	private static String checkNameLength() {
이부분도 저번에 말씀드렸던 부분인데 수정이 하나도 안되어있네요. input에서 객체를 생성해야되는 이유가 있을까요? 코멘트를 달아주세요
mvc개념에 대해서 다시한번 보시기 바랍니다.

2021-09-23 05:50 UTC, pih6585 commented on src/main/java/dice/view/InputView.java
> +		boolean english = name.matches("^[a-zA-Z]*$");
여기서 체크하는 method도 위에 말씀드린것과 마찬가지 입니다.

2021-09-23 05:50 UTC, pih6585 commented on src/main/java/dice/view/ResultView.java
> +	public static final String RESULT_MESSAGE = "실행결과";
접근제어자가 public이네요 신경써주세요

2021-09-23 05:50 UTC, pih6585 commented on src/main/java/dice/view/ResultView.java
> +	public static void resultGameState(List<PlayerScore> scoreByPlayer) {
파라미터의 method명이 이상합니다. 코딩 컨벤션의 naming 규칙을 지켜주세요

2021-09-23 05:50 UTC, pih6585 commented on src/main/java/dice/view/ResultView.java
> +				scoreByPlayer.get(i).getFirstDice() + " - " +
여기서도 출력물이 특정한 패턴을 가지고 있는데 이런 패턴들을 활용 할 수 있도록 고쳐보는것도 좋은 방법입니다.

2021-09-23 05:50 UTC, pih6585 commented on src/main/java/dice/view/ResultView.java
> +				scoreByPlayer.get(i).getFirstDice() + " - " +
여기서도 상수를 이용해보세요

2021-09-23 05:51 UTC, pih6585 commented
테스트코드가 전체적으로 구현이 되지가 않았아요. 
Dice는 Dice에 대한 Test가 없고 각 클래스마다 테스트 코드 가 없네요
그리고 커밋은 기능 별 커밋메세지를 작성해주세요.

2021-09-23 13:11 UTC, kth4878 commented on src/main/java/dice/domain/DiceResult.java
> +	private final int diceResult;
생성자를 무조건 사용해서 값을 받으려고 해서 new 를 사용했습니다.
randomResult method를 static로 사용해 new DiceResult를 하지 않도록 수정하겠습니다.

2021-09-28 07:17 UTC, pih6585 approved these changes

2021-09-28 07:17 UTC, pih6585 commented on src/main/java/dice/domain/Name.java
> +		if (!english) {
이부분은 하나로 합치고 ! -> not인 부분을 matches에서 해주는게 가독성에 좋겟죠?

2021-09-28 07:17 UTC, pih6585 commented on src/main/java/dice/view/InputView.java
> +		if (names.size() != names.stream().distinct().count()) {
이런부분은 개행을 해서 가독성을 높이는게 좋아요

2021-09-28 07:17 UTC, merged